import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { fileURLToPath, URL } from 'url'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      // eslint-disable-next-line @typescript-eslint/naming-convention
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  server: {
    port: 3000,
    host: '0.0.0.0', // 解决不能通过ip访问
    // cors: true, // 默认启用并允许任何源
    proxy: {
      '/api': {
        target: 'http://mh.helloworlds.xyz/app.php', //实际请求地址
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, '')
      }
    }
  },
  // build: {
  //   rollupOptions: {
  //     // This is for the code generated by decorators. If we don't specify this,
  //     // it defaults to globalThis, which older android phones won't understand.
  //     context: 'window'
  //   },
  //   sourcemap: process.env.NODE_ENV !== 'production'
  // }
})
